### ISSUE TITLE
ansible won't run from the launched ec2 instances

### ISSUE THREAD

**Issue by EslamElHusseiny** [balanced-ops/infra-zookeeper#8]
Ansible won't run from any launched ec2 instance as the ansible  run command is : 
`./env/bin/ansible-playbook site.yml -i inventories/pull -c local`

and inventories/pull depends on confu library which isn't installed on launched instances 

I've tried to run the following command on one of the launched ec2 instances to double check, the command is : 
`python inventories/pull`
and the output was as following : 

```
Traceback (most recent call last):
 File "inventories/pull", line 7, in <module>
   from confu import aws, ansible
ImportError: No module named confu
```

**Comment by mjallday** [comment]
I tried it on an already running machine and it works as expected. 

Were you missing any of the submodules that need to be checked out when you built the tarball that it downloaded?

If you want to run the inventory script directly you will need to use the virtualenv python, not the system python. e.g. `./env/bin/python inventories/pull`
